//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  D:\Akhilesh\25.02.2026\TransformPath\TransformPath\bin\Debug\Transform_Path_UI.cs
//
//        This file was generated by the NX Block UI Styler
//        Created by: Sun16
//              Version: NX 2306
//              Date: 02-25-2026  (Format: mm-dd-yyyy)
//              Time: 15:44 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//  Purpose:  This TEMPLATE file contains C# source to guide you in the
//  construction of your Block application dialog. The generation of your
//  dialog file (.dlx extension) is the first step towards dialog construction
//  within NX.  You must now create a NX Open application that
//  utilizes this file (.dlx).
//
//  The information in this file provides you with the following:
//
//  1.  Help on how to load and display your Block UI Styler dialog in NX
//      using APIs provided in NXOpen.BlockStyler namespace
//  2.  The empty callback methods (stubs) associated with your dialog items
//      have also been placed in this file. These empty methods have been
//      created simply to start you along with your coding requirements.
//      The method name, argument list and possible return values have already
//      been provided for you.
//==============================================================================

//------------------------------------------------------------------------------
//These imports are needed for the following template code
//------------------------------------------------------------------------------
using System;
using NXOpen;
using NXOpen.BlockStyler;
using System.Linq;
using NXOpen.Routing;

//------------------------------------------------------------------------------
//Represents Block Styler application class
//------------------------------------------------------------------------------
public class Transform_Path_UI
{
    //class members
    private static Session theSession = null;
    private static UI theUI = null;
    private string theDlxFileName;
    private NXOpen.BlockStyler.BlockDialog theDialog;
    private NXOpen.BlockStyler.Group routingObjectGroup;// Block type: Group
    private NXOpen.BlockStyler.SelectObject routingObject;// Block type: Selection
    private NXOpen.BlockStyler.Group transformGroup;// Block type: Group
    private NXOpen.BlockStyler.Enumeration enumMotion;// Block type: Enumeration
    private NXOpen.BlockStyler.Group groupAlongCurveAngle;// Block type: Group
    private NXOpen.BlockStyler.SelectObject selectCurveACA;// Block type: Selection
    private NXOpen.BlockStyler.ReverseDirection directionAlongCurveACA;// Block type: Reverse Direction
    private NXOpen.BlockStyler.OnPathDimension on_path_dimACA;// Block type: On Path Dim
    private NXOpen.BlockStyler.AngularDimension angularDimACA;// Block type: Angular Dim
    private NXOpen.BlockStyler.Group groupDistanceAngle;// Block type: Group
    private NXOpen.BlockStyler.SpecifyVector distanceVectorDA;// Block type: Specify Vector
    private NXOpen.BlockStyler.SpecifyPoint pivotPointDA;// Block type: Specify Point
    private NXOpen.BlockStyler.LinearDimension distanceDA;// Block type: Linear Dim
    private NXOpen.BlockStyler.AngularDimension angleDA;// Block type: Angular Dim
    private NXOpen.BlockStyler.Group groupDistance;// Block type: Group
    private NXOpen.BlockStyler.SpecifyVector vectorSelectD;// Block type: Specify Vector
    private NXOpen.BlockStyler.LinearDimension distanceD;// Block type: Linear Dim
    private NXOpen.BlockStyler.Group groupAngle;// Block type: Group
    private NXOpen.BlockStyler.SpecifyVector vectorA;// Block type: Specify Vector
    private NXOpen.BlockStyler.SpecifyPoint axisPointA;// Block type: Specify Point
    private NXOpen.BlockStyler.AngularDimension angular_dimA;// Block type: Angular Dim
    private NXOpen.BlockStyler.Group groupDistanceBetweenPoints;// Block type: Group
    private NXOpen.BlockStyler.SpecifyPoint originPointDBP;// Block type: Specify Point
    private NXOpen.BlockStyler.SpecifyPoint measurementPointDBP;// Block type: Specify Point
    private NXOpen.BlockStyler.SpecifyVector vectorDBP;// Block type: Specify Vector
    private NXOpen.BlockStyler.LinearDimension distanceDBP;// Block type: Linear Dim
    private NXOpen.BlockStyler.Group groupRadialDistance;// Block type: Group
    private NXOpen.BlockStyler.SpecifyVector vectorRD;// Block type: Specify Vector
    private NXOpen.BlockStyler.SpecifyPoint axisPointRD;// Block type: Specify Point
    private NXOpen.BlockStyler.SpecifyPoint measurementPointRD;// Block type: Specify Point
    private NXOpen.BlockStyler.LinearDimension distanceRD;// Block type: Linear Dim
    private NXOpen.BlockStyler.Group groupPointToPoint;// Block type: Group
    private NXOpen.BlockStyler.SpecifyPoint fromPointPTP;// Block type: Specify Point
    private NXOpen.BlockStyler.SpecifyPoint toPointPTP;// Block type: Specify Point
    private NXOpen.BlockStyler.Group groupRotateByThreePoints;// Block type: Group
    private NXOpen.BlockStyler.SpecifyVector vectorRBTP;// Block type: Specify Vector
    private NXOpen.BlockStyler.SpecifyPoint pivotPointRBTP;// Block type: Specify Point
    private NXOpen.BlockStyler.SpecifyPoint startPointRBTP;// Block type: Specify Point
    private NXOpen.BlockStyler.SpecifyPoint endPointRBTP;// Block type: Specify Point
    private NXOpen.BlockStyler.Group groupAlignAxisToVector;// Block type: Group
    private NXOpen.BlockStyler.SpecifyVector fromVectorAATV;// Block type: Specify Vector
    private NXOpen.BlockStyler.SpecifyPoint pivotPointAATV;// Block type: Specify Point
    private NXOpen.BlockStyler.SpecifyVector toVectorAATV;// Block type: Specify Vector
    private NXOpen.BlockStyler.Group resultGroup;// Block type: Group
    private NXOpen.BlockStyler.Enumeration enumResultList;// Block type: Enumeration
    private NXOpen.BlockStyler.Group moveOriginalGroup;// Block type: Group
    private NXOpen.BlockStyler.Group copyOriginalGroup;// Block type: Group
    private NXOpen.BlockStyler.IntegerBlock numOfCopies;// Block type: Integer
    //------------------------------------------------------------------------------
    //Bit Option for Property: SnapPointTypesEnabled
    //------------------------------------------------------------------------------
    public static readonly int              SnapPointTypesEnabled_UserDefined = (1 << 0);
    public static readonly int                 SnapPointTypesEnabled_Inferred = (1 << 1);
    public static readonly int           SnapPointTypesEnabled_ScreenPosition = (1 << 2);
    public static readonly int                 SnapPointTypesEnabled_EndPoint = (1 << 3);
    public static readonly int                 SnapPointTypesEnabled_MidPoint = (1 << 4);
    public static readonly int             SnapPointTypesEnabled_ControlPoint = (1 << 5);
    public static readonly int             SnapPointTypesEnabled_Intersection = (1 << 6);
    public static readonly int                SnapPointTypesEnabled_ArcCenter = (1 << 7);
    public static readonly int            SnapPointTypesEnabled_QuadrantPoint = (1 << 8);
    public static readonly int            SnapPointTypesEnabled_ExistingPoint = (1 << 9);
    public static readonly int             SnapPointTypesEnabled_PointonCurve = (1 <<10);
    public static readonly int           SnapPointTypesEnabled_PointonSurface = (1 <<11);
    public static readonly int         SnapPointTypesEnabled_PointConstructor = (1 <<12);
    public static readonly int     SnapPointTypesEnabled_TwocurveIntersection = (1 <<13);
    public static readonly int             SnapPointTypesEnabled_TangentPoint = (1 <<14);
    public static readonly int                    SnapPointTypesEnabled_Poles = (1 <<15);
    public static readonly int         SnapPointTypesEnabled_BoundedGridPoint = (1 <<16);
    public static readonly int         SnapPointTypesEnabled_FacetVertexPoint = (1 <<17);
    public static readonly int            SnapPointTypesEnabled_DefiningPoint = (1 <<18);
    //------------------------------------------------------------------------------
    //Bit Option for Property: SnapPointTypesOnByDefault
    //------------------------------------------------------------------------------
    public static readonly int             SnapPointTypesOnByDefault_EndPoint = (1 << 3);
    public static readonly int             SnapPointTypesOnByDefault_MidPoint = (1 << 4);
    public static readonly int         SnapPointTypesOnByDefault_ControlPoint = (1 << 5);
    public static readonly int         SnapPointTypesOnByDefault_Intersection = (1 << 6);
    public static readonly int            SnapPointTypesOnByDefault_ArcCenter = (1 << 7);
    public static readonly int        SnapPointTypesOnByDefault_QuadrantPoint = (1 << 8);
    public static readonly int        SnapPointTypesOnByDefault_ExistingPoint = (1 << 9);
    public static readonly int         SnapPointTypesOnByDefault_PointonCurve = (1 <<10);
    public static readonly int       SnapPointTypesOnByDefault_PointonSurface = (1 <<11);
    public static readonly int     SnapPointTypesOnByDefault_PointConstructor = (1 <<12);
    public static readonly int     SnapPointTypesOnByDefault_BoundedGridPoint = (1 <<16);
    public static readonly int     SnapPointTypesOnByDefault_FacetVertexPoint = (1 <<17);
    //------------------------------------------------------------------------------
    //Bit Option for Property: SnapPointTypesOnByDefault
    //------------------------------------------------------------------------------
    public static readonly int          SnapPointTypesOnByDefault_UserDefined = (1 << 0);
    public static readonly int             SnapPointTypesOnByDefault_Inferred = (1 << 1);
    public static readonly int       SnapPointTypesOnByDefault_ScreenPosition = (1 << 2);
    public static readonly int SnapPointTypesOnByDefault_TwocurveIntersection = (1 <<13);
    public static readonly int         SnapPointTypesOnByDefault_TangentPoint = (1 <<14);
    public static readonly int                SnapPointTypesOnByDefault_Poles = (1 <<15);
    public static readonly int        SnapPointTypesOnByDefault_DefiningPoint = (1 <<18);
    //------------------------------------------------------------------------------
    //Bit Option for Property: OptionMask
    //------------------------------------------------------------------------------
    public static readonly int                              OptionMask_Length = (1 << 0);
    public static readonly int                             OptionMask_Percent = (1 << 1);
    public static readonly int                           OptionMask_Parameter = (1 << 2);
    public static readonly int                        OptionMask_ThroughPoint = (1 << 3);
    
    //------------------------------------------------------------------------------
    //Constructor for NX Styler class
    //------------------------------------------------------------------------------
    public Transform_Path_UI()
    {
        try
        {
            theSession = Session.GetSession();
            theUI = UI.GetUI();
            theDlxFileName = "Transform_Path_UI.dlx";
            theDialog = theUI.CreateDialog(System.IO.Path.Combine(AppContext.BaseDirectory, theDlxFileName));
            theDialog.AddApplyHandler(new NXOpen.BlockStyler.BlockDialog.Apply(apply_cb));
            theDialog.AddOkHandler(new NXOpen.BlockStyler.BlockDialog.Ok(ok_cb));
            theDialog.AddUpdateHandler(new NXOpen.BlockStyler.BlockDialog.Update(update_cb));
            theDialog.AddInitializeHandler(new NXOpen.BlockStyler.BlockDialog.Initialize(initialize_cb));
            theDialog.AddDialogShownHandler(new NXOpen.BlockStyler.BlockDialog.DialogShown(dialogShown_cb));
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            throw ex;
        }
    }
    //------------------------------- DIALOG LAUNCHING ---------------------------------
    //
    //    Before invoking this application one needs to open any part/empty part in NX
    //    because of the behavior of the blocks.
    //
    //    Make sure the dlx file is in one of the following locations:
    //        1.) From where NX session is launched
    //        2.) $UGII_USER_DIR/application
    //        3.) For released applications, using UGII_CUSTOM_DIRECTORY_FILE is highly
    //            recommended. This variable is set to a full directory path to a file 
    //            containing a list of root directories for all custom applications.
    //            e.g., UGII_CUSTOM_DIRECTORY_FILE=$UGII_BASE_DIR\ugii\menus\custom_dirs.dat
    //
    //    You can create the dialog using one of the following way:
    //
    //    1. Journal Replay
    //
    //        1) Replay this file through Tool->Journal->Play Menu.
    //
    //    2. USER EXIT
    //
    //        1) Create the Shared Library -- Refer "Block UI Styler programmer's guide"
    //        2) Invoke the Shared Library through File->Execute->NX Open menu.
    //
    //------------------------------------------------------------------------------
    public static void Main()
    {
        Transform_Path_UI theTransform_Path_UI = null;
        try
        {
            theTransform_Path_UI = new Transform_Path_UI();
            // The following method shows the dialog immediately
            theTransform_Path_UI.Launch();
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        finally
        {
            if(theTransform_Path_UI != null)
                theTransform_Path_UI.Dispose();
                theTransform_Path_UI = null;
        }
    }
    //------------------------------------------------------------------------------
    // This method specifies how a shared image is unloaded from memory
    // within NX. This method gives you the capability to unload an
    // internal NX Open application or user  exit from NX. Specify any
    // one of the three constants as a return value to determine the type
    // of unload to perform:
    //
    //
    //    Immediately : unload the library as soon as the automation program has completed
    //    Explicitly  : unload the library from the "Unload Shared Image" dialog
    //    AtTermination : unload the library when the NX session terminates
    //
    //
    // NOTE:  A program which associates NX Open applications with the menubar
    // MUST NOT use this option since it will UNLOAD your NX Open application image
    // from the menubar.
    //------------------------------------------------------------------------------
     public static int GetUnloadOption(string arg)
    {
        //return System.Convert.ToInt32(Session.LibraryUnloadOption.Explicitly);
         return System.Convert.ToInt32(Session.LibraryUnloadOption.Immediately);
        // return System.Convert.ToInt32(Session.LibraryUnloadOption.AtTermination);
    }
    
    //------------------------------------------------------------------------------
    // Following method cleanup any housekeeping chores that may be needed.
    // This method is automatically called by NX.
    //------------------------------------------------------------------------------
    public static void UnloadLibrary(string arg)
    {
        try
        {
            //---- Enter your code here -----
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }
    
    //------------------------------------------------------------------------------
    //This method launches the dialog to screen
    //------------------------------------------------------------------------------
    public NXOpen.BlockStyler.BlockDialog.DialogResponse Launch()
    {
        NXOpen.BlockStyler.BlockDialog.DialogResponse dialogResponse = NXOpen.BlockStyler.BlockDialog.DialogResponse.Invalid;
        try
        {
            dialogResponse = theDialog.Launch();
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return dialogResponse;
    }
    
    //------------------------------------------------------------------------------
    //Method Name: Dispose
    //------------------------------------------------------------------------------
    public void Dispose()
    {
        if(theDialog != null)
        {
            theDialog.Dispose();
            theDialog = null;
        }
    }
    
    //------------------------------------------------------------------------------
    //---------------------Block UI Styler Callback Functions--------------------------
    //------------------------------------------------------------------------------
    
    //------------------------------------------------------------------------------
    //Callback Name: initialize_cb
    //------------------------------------------------------------------------------
    public void initialize_cb()
    {
        try
        {
            routingObjectGroup = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("routingObjectGroup");
            routingObject = (NXOpen.BlockStyler.SelectObject)theDialog.TopBlock.FindBlock("routingObject");
            transformGroup = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("transformGroup");
            enumMotion = (NXOpen.BlockStyler.Enumeration)theDialog.TopBlock.FindBlock("enumMotion");
            groupAlongCurveAngle = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("groupAlongCurveAngle");
            selectCurveACA = (NXOpen.BlockStyler.SelectObject)theDialog.TopBlock.FindBlock("selectCurveACA");
            directionAlongCurveACA = (NXOpen.BlockStyler.ReverseDirection)theDialog.TopBlock.FindBlock("directionAlongCurveACA");
            on_path_dimACA = (NXOpen.BlockStyler.OnPathDimension)theDialog.TopBlock.FindBlock("on_path_dimACA");
            angularDimACA = (NXOpen.BlockStyler.AngularDimension)theDialog.TopBlock.FindBlock("angularDimACA");
            groupDistanceAngle = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("groupDistanceAngle");
            distanceVectorDA = (NXOpen.BlockStyler.SpecifyVector)theDialog.TopBlock.FindBlock("distanceVectorDA");
            pivotPointDA = (NXOpen.BlockStyler.SpecifyPoint)theDialog.TopBlock.FindBlock("pivotPointDA");
            distanceDA = (NXOpen.BlockStyler.LinearDimension)theDialog.TopBlock.FindBlock("distanceDA");
            angleDA = (NXOpen.BlockStyler.AngularDimension)theDialog.TopBlock.FindBlock("angleDA");
            groupDistance = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("groupDistance");
            vectorSelectD = (NXOpen.BlockStyler.SpecifyVector)theDialog.TopBlock.FindBlock("vectorSelectD");
            distanceD = (NXOpen.BlockStyler.LinearDimension)theDialog.TopBlock.FindBlock("distanceD");
            groupAngle = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("groupAngle");
            vectorA = (NXOpen.BlockStyler.SpecifyVector)theDialog.TopBlock.FindBlock("vectorA");
            axisPointA = (NXOpen.BlockStyler.SpecifyPoint)theDialog.TopBlock.FindBlock("axisPointA");
            angular_dimA = (NXOpen.BlockStyler.AngularDimension)theDialog.TopBlock.FindBlock("angular_dimA");
            groupDistanceBetweenPoints = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("groupDistanceBetweenPoints");
            originPointDBP = (NXOpen.BlockStyler.SpecifyPoint)theDialog.TopBlock.FindBlock("originPointDBP");
            measurementPointDBP = (NXOpen.BlockStyler.SpecifyPoint)theDialog.TopBlock.FindBlock("measurementPointDBP");
            vectorDBP = (NXOpen.BlockStyler.SpecifyVector)theDialog.TopBlock.FindBlock("vectorDBP");
            distanceDBP = (NXOpen.BlockStyler.LinearDimension)theDialog.TopBlock.FindBlock("distanceDBP");
            groupRadialDistance = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("groupRadialDistance");
            vectorRD = (NXOpen.BlockStyler.SpecifyVector)theDialog.TopBlock.FindBlock("vectorRD");
            axisPointRD = (NXOpen.BlockStyler.SpecifyPoint)theDialog.TopBlock.FindBlock("axisPointRD");
            measurementPointRD = (NXOpen.BlockStyler.SpecifyPoint)theDialog.TopBlock.FindBlock("measurementPointRD");
            distanceRD = (NXOpen.BlockStyler.LinearDimension)theDialog.TopBlock.FindBlock("distanceRD");
            groupPointToPoint = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("groupPointToPoint");
            fromPointPTP = (NXOpen.BlockStyler.SpecifyPoint)theDialog.TopBlock.FindBlock("fromPointPTP");
            toPointPTP = (NXOpen.BlockStyler.SpecifyPoint)theDialog.TopBlock.FindBlock("toPointPTP");
            groupRotateByThreePoints = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("groupRotateByThreePoints");
            vectorRBTP = (NXOpen.BlockStyler.SpecifyVector)theDialog.TopBlock.FindBlock("vectorRBTP");
            pivotPointRBTP = (NXOpen.BlockStyler.SpecifyPoint)theDialog.TopBlock.FindBlock("pivotPointRBTP");
            startPointRBTP = (NXOpen.BlockStyler.SpecifyPoint)theDialog.TopBlock.FindBlock("startPointRBTP");
            endPointRBTP = (NXOpen.BlockStyler.SpecifyPoint)theDialog.TopBlock.FindBlock("endPointRBTP");
            groupAlignAxisToVector = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("groupAlignAxisToVector");
            fromVectorAATV = (NXOpen.BlockStyler.SpecifyVector)theDialog.TopBlock.FindBlock("fromVectorAATV");
            pivotPointAATV = (NXOpen.BlockStyler.SpecifyPoint)theDialog.TopBlock.FindBlock("pivotPointAATV");
            toVectorAATV = (NXOpen.BlockStyler.SpecifyVector)theDialog.TopBlock.FindBlock("toVectorAATV");
            resultGroup = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("resultGroup");
            enumResultList = (NXOpen.BlockStyler.Enumeration)theDialog.TopBlock.FindBlock("enumResultList");
            moveOriginalGroup = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("moveOriginalGroup");
            copyOriginalGroup = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("copyOriginalGroup");
            numOfCopies = (NXOpen.BlockStyler.IntegerBlock)theDialog.TopBlock.FindBlock("numOfCopies");
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }

    //------------------------------------------------------------------------------
    //Callback Name: dialogShown_cb
    //This callback is executed just before the dialog launch. Thus any value set 
    //here will take precedence and dialog will be launched showing that value. 
    //------------------------------------------------------------------------------
    public void dialogShown_cb()
    {
        try
        {
            // Set initial visibility for Motion groups
            update_cb(enumMotion);

            // Set initial visibility for Copy Original logic
            update_cb(enumResultList);
        }
        catch (Exception ex)
        {
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }

    //------------------------------------------------------------------------------
    //Callback Name: apply_cb
    //------------------------------------------------------------------------------
    public int apply_cb()
    {
        int errorCode = 0;
        NXOpen.Session.UndoMarkId markId = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Visible, "Transform Path");

        try
        {
            NXOpen.Part workPart = theSession.Parts.Work;

            // 1. Get Selected Routing Objects
            NXObject[] selectedObjects = routingObject.GetSelectedObjects().Cast<NXObject>().ToArray();
            if (selectedObjects.Length == 0) return 0;
            NXOpen.BlockStyler.SelectObject selectObj =
                (NXOpen.BlockStyler.SelectObject)theDialog.TopBlock.FindBlock("routing_object");

            //NXObject[] selectedObjects = selectObj.GetSelectedObjects();

            if (selectedObjects == null || selectedObjects.Length == 0)
            {
                theUI.NXMessageBox.Show("Error", NXMessageBox.DialogType.Error,
                    "Please select routing object.");
                return 1;
            }

            RouteManager routeManager = workPart.RouteManager;

            TransformPathBuilder builder =
                routeManager.CreateTransformPathBuilder(selectedObjects);

            //NXOpen.Routing.TransformPathBuilder builder =
               // workPart.RouteManager.CreateTransformPathBuilder(null);
            builder.PathSelection.RoutingObjects.Add(selectedObjects[0]);
            builder.AttachSelectedPath();
            builder.UpdateSelObjectsVector();
            builder.PathSelection.RoutingObjects.Add(selectedObjects[0]);
            builder.AttachSelectedPath();
            builder.UpdateSelObjectsVector();

            // 3. Set Move vs Copy Logic (from your enumResultList)
            int resultIndex = enumResultList.GetProperties().GetEnum("Value");
            if (resultIndex == 1) // Copy
            {
                builder.MoveOrCopyOption = NXOpen.Routing.TransformPathBuilder.TransformOption.CopyOriginal;
                builder.NumberOfCopies = numOfCopies.Value;
            }
            else // Move
            {
                builder.MoveOrCopyOption = NXOpen.Routing.TransformPathBuilder.TransformOption.MoveOriginal;
            }

            // 4. Handle the 9 Motion Scenarios
            int motionIndex = enumMotion.GetProperties().GetEnum("Value");

            switch (motionIndex)
            {
                /*case 0: // Along Curve Angle
                    SetupAlongCurveAngle(builder);
                    break;
                */

                case 2: // Distance (The one from your journal)
                    SetupDistanceMove(builder);
                    break;

                /*case 6: // Point to Point
                    etupPointToPoint(builder);
                    break;
                */

                    // Add cases 1, 3, 4, 5, 7, 8 here as you develop them
            }

            // 5. Commit the changes
            builder.Commit();
            builder.Destroy();

        }
        catch (Exception ex)
        {
            errorCode = 1;
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
            theSession.UndoToMark(markId, "Transform Path Error");
        }
        return errorCode;
    }

    //------------------------------------------------------------------------------
    //Callback Name: update_cb
    //------------------------------------------------------------------------------
    public int update_cb(NXOpen.BlockStyler.UIBlock block)
    {
        try
        {
            if (block == routingObject)
            {
            }
            else if (block == enumMotion)
            {
                int selIndex = enumMotion.GetProperties().GetEnum("Value");

                // Hide all groups first
                groupAlongCurveAngle.Show = false;
                groupDistanceAngle.Show = false;
                groupDistance.Show = false;
                groupAngle.Show = false;
                groupDistanceBetweenPoints.Show = false;
                groupRadialDistance.Show = false;
                groupPointToPoint.Show = false;
                groupRotateByThreePoints.Show = false;
                groupAlignAxisToVector.Show = false;

                // Show selected group
                switch (selIndex)
                {
                    case 0: groupAlongCurveAngle.Show = true; break;
                    case 1: groupDistanceAngle.Show = true; break;
                    case 2: groupDistance.Show = true; break;
                    case 3: groupAngle.Show = true; break;
                    case 4: groupDistanceBetweenPoints.Show = true; break;
                    case 5: groupRadialDistance.Show = true; break;
                    case 6: groupPointToPoint.Show = true; break;
                    case 7: groupRotateByThreePoints.Show = true; break;
                    case 8: groupAlignAxisToVector.Show = true; break;
                }
            }
            else if (block == enumResultList)
            {
                // Get the index from the Move/Copy radio buttons
                int resultIndex = enumResultList.GetProperties().GetEnum("Value");

                // If index is 1 (Copy Original), show the number of copies
                // If index is 0 (Move Original), hide it
                if (resultIndex == 1)
                {
                    numOfCopies.Show = true;
                }
                else
                {
                    numOfCopies.Show = false;
                }
            }
        }
        catch (Exception ex)
        {
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return 0;
    }

    //------------------------------------------------------------------------------
    //Callback Name: ok_cb
    //------------------------------------------------------------------------------
    public int ok_cb()
    {
        int errorCode = 0;
        try
        {
            errorCode = apply_cb();
            //---- Enter your callback code here -----
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            errorCode = 1;
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return errorCode;
    }
    
    //------------------------------------------------------------------------------
    //Function Name: GetBlockProperties
    //Returns the propertylist of the specified BlockID
    //------------------------------------------------------------------------------
    public PropertyList GetBlockProperties(string blockID)
    {
        PropertyList plist =null;
        try
        {
            plist = theDialog.GetBlockProperties(blockID);
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return plist;
    }
    /*private void SetupDistanceMove(NXOpen.Routing.TransformPathBuilder builder)
    {
        NXOpen.Part workPart = theSession.Parts.Work;

        // Set the builder option to Distance
        builder.Transform.Option = NXOpen.GeometricUtilities.ModlMotion.Options.Distance;

        // 1. Get Vector (this part is usually fine)
        Vector3d dirVec = vectorSelectD.Vector;

        // 2. CHANGE "Origin" TO "Point" HERE
        // This is the line that was causing the "Invalid property name" error
        Point3d origin = vectorSelectD.GetProperties().GetPoint("Point");

        // 3. Create the Direction object
        Direction distDir = workPart.Directions.CreateDirection(origin, dirVec, SmartObject.UpdateOption.WithinModeling);
        builder.Transform.DistanceVector = distDir;

        // 4. Set the Distance value
        builder.Transform.DistanceValue.SetFormula(distanceD.Value.ToString());
        theUI.NXMessageBox.Show("Debug",
        NXMessageBox.DialogType.Information,
        "Distance = " + distanceD.Value.ToString());
    }
    */

    private void SetupDistanceMove(TransformPathBuilder builder)
    {
        NXOpen.Part workPart = theSession.Parts.Work;

        // 1️⃣ Set transform option properly
        builder.Transform.TransformOption =
            NXOpen.Routing.TransformPathBuilder.TransformOption.Distance;

        // 2️⃣ Get direction from vector block
        Vector3d dirVec = vectorSelectD.Vector;
        Point3d origin = vectorSelectD.Point;

        Direction distDir =
            workPart.Directions.CreateDirection(
                origin,
                dirVec,
                SmartObject.UpdateOption.WithinModeling);

        builder.Transform.DistanceVector = distDir;

        // 3️⃣ Set numeric distance
        builder.Transform.DistanceValue.Value = distanceD.Value;
    }

}
